### ISSUE TITLE
Display incorrect macOS Sonoma, macOS Ventura version for all latest version as 10.15

### ISSUE THREAD

**Issue by deepaknsp11** [faisalman/ua-parser-js#716] opened 2024-03-14 15:45 UTC
Which version of the library that you use, **UAParser.js v2.0.0-beta.2**

For the issue related with detection result, you can use the demo section in https://uaparser.js.org to confirm

**Describe the bug**
I am using the UAParse Js to detect the mac OS version but it always return 10.15 for macOS Sonoma, macOS Ventura etc even these are latest version 14, 13 respectively

**To Reproduce**
1. Go to Mac Os macOS Ventura
2. Click on https://www.truetraveller.com/UnsupportedmacOS.html
3. Check in console 
4. It always return 10.15 for higher version of Mac OS

**Expected behavior**
It should return correct version of the MacOS

**Screenshots**
Attached console screen shot for latest MacOS return default 10.15

**Desktop (please complete the following information):**
 - OS: Mac OS Sonoma
![ScreenShot_1](https://github.com/faisalman/ua-parser-js/assets/22102495/3ff9ab98-8b09-4135-b427-9d5544342952)

 - Browser chrome
 - Version 122

**Smartphone (please complete the following information):**

**Additional context**

**Comment by deepaknsp11** [comment] 2024-03-19 15:03
Is there any way we can get the correct version?

**Comment by nickdnk** [comment] 2024-03-19 15:10
See https://github.com/faisalman/ua-parser-js/issues/659 - your issue is essentially a duplicate.

**Comment by faisalman** [comment] 2024-06-02 13:02
Duplicate of #659

**Closed by faisalman** 2024-06-02 13:02 UTC
