### ISSUE TITLE
iOS/iPadOS detected as Mac OS

### ISSUE THREAD

**Issue by tpetry** [faisalman/ua-parser-js#417] opened 2020-03-09 12:37 UTC
There's a problem detecting iPads with iPad OS (>= 13.x) and any iOS version when requesting the desktop site.

The user agent of normal iOS ipads is looking like this (correctly recognized):
``
Mozilla/5.0 (iPad; CPU OS 12_4_5 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Mobile/15E148
``

But when requesting the desktop site (with iOS 12) or iPad OS 13 this user agent is transmitted:
``
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_5) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/12.1.1 Safari/605.1.15
``
``
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_1) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.0.3 Safari/605.1.15
``

So ua-parser is seeing the `Mac OS X` information in the user agent and no longer any iPad information so the user agent is wrongly identified as desktop Mac OS X client.

But as you can see, the **real** MacOS user agent is a little bit different:
``
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_1) AppleWebKit/605.1.15 (KHTML, like Gecko)
``

The `Version/x.y.z` information is only present for iOS/iPadOS devices, not for MacOS X devices. But sadly the differentiation from iOS (smartphone) to iPad OS (tablet) is not possible. But maybe it could transport the information that it's an mobile device requesting the desktop site? Because most often it will be an iPadOS because it's now requesting it on default, for iOS the user has to request the desktop site manually everytime.

**Comment by vykimo** [comment] 2020-04-26 17:48
Related issue : https://github.com/faisalman/ua-parser-js/issues/387

**Comment by faisalman** [comment] 2021-03-17 15:40
Nice catch, but can it be confirmed that for any Mac user agent with `Version/x.y.z` they must be originated from iOS/iPadOS _only_? Because what I found here: https://www.whatismybrowser.com/guides/the-latest-user-agent/safari suggests otherwise.

> Related issue : #387

Since the topic is kind of similar, I'm moving this discussion there as I think this finding might be useful there

**Closed by faisalman** 2021-03-17 15:40 UTC
