### ISSUE TITLE
Hbbtv version

### ISSUE THREAD

**Issue by garritfra** [faisalman/ua-parser-js#607] opened 2022-11-07 15:26 UTC
Hi,

we're planning to integrate this library into a service that resolves smart tv user agents. The library currently just seems to be able to tell if the UA is a smart tv, but not its Hbbtv version, if applicable.

Are you open to contributions addressing this rather niche problem?

If so, I'm unsure where this information could be placed.
An obvious solution would be to add it to the root of the object:

```json
{
  "ua": "",
  "browser": {},
  "engine": {},
  "os": {},
  "device": {},
  "cpu": {}
  "hbbtv": {
    "version": "1.1.1"
  }
}
```

I'm very open for remarks, since this approach potentially pollutes the object returned by the library.

**Comment by faisalman** [comment] 2022-12-06 02:28
Hi @garritfra thanks for the suggestion, I'm very open to contributions that can improve the current identification of Smart TVs, but to add a new feature, especially if the problem is rather niche, it's something that would require some assessment on its benefits for most user of this library.

**Comment by garritfra** [comment] 2022-12-09 12:47
@faisalman Thanks for your feedback. #618 is a new PR, which only adds support for various smart tv user agents, without a new `hbbtv` section in the result.

**Comment by faisalman** [comment] 2023-01-29 02:48
Merged. Thanks :+1:

**Closed by faisalman** 2023-01-29 02:48 UTC
