### ISSUE TITLE
Safari 15.7 - Browser version not parsed

### ISSUE THREAD

**Issue by jb00ster** [faisalman/ua-parser-js#599] opened 2022-09-27 13:33 UTC
on iPhone 11 with Safari 15.7 with the userAgent below
`Mozilla/5.0 (iPhone; CPU iPhone OS 15_7 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.6,2 Mobile/15E148 Safari/604.1`
the browser version returned by the lib is undefined
it seems like the lib doesn't like the comma in the version "15.6,2"`
```
{
    "ua": "Mozilla/5.0 (iPhone; CPU iPhone OS 15_7 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.6,2 Mobile/15E148 Safari/604.1",
    "browser": {
        "name": "Safari"
    },
    "engine": {
        "name": "WebKit",
        "version": "605.1.15"
    },
    "os": {
        "name": "iOS",
        "version": "15.7"
    },
    "device": {
        "vendor": "Apple",
        "model": "iPhone",
        "type": "mobile"
    },
    "cpu": {}
}
```

**Comment by nickvergessen** [comment] 2022-10-10 09:47
Duplicate of https://github.com/faisalman/ua-parser-js/issues/594
Fixed by https://github.com/faisalman/ua-parser-js/pull/595

just needs a new release it seems.

**Comment by faisalman** [comment] 2022-10-15 10:01
Done

**Closed by faisalman** 2022-10-15 10:01 UTC

**Comment by nickvergessen** [comment] 2022-10-17 06:51
Thanks a lot! 🎉
