### ISSUE TITLE
Feature request: isMobile / isTablet / isDesktop

### ISSUE THREAD

**Issue by ChristianRich** [faisalman/ua-parser-js#155] opened 2015-12-01 03:30 UTC
I've been using your library for a long time and it totally rocks.
However I always seem to add in three extra computated results:

* {Boolean} isMobile
* {Boolean} isTablet
* {Boolean} isDesktop

Would it be possible to add these additional keys to the result?

Thanks,
Christian

**Comment by faisalman** [comment] 2015-12-12 05:25
Hi Christian, thank you, interesting idea but currently I have no plan to add more extras to the result object.

I'll close this issue as duplicate of #135

**Closed by faisalman** 2015-12-12 05:25 UTC

**Comment by ChristianRich** [comment] 2015-12-13 05:30
Okay no problem. I might do a fork and add this my self then :-)

**Comment by faisalman** [comment] 2024-11-08 03:23
Since version `2.0.0` you can use `is()`[^1]:

```js
getDevice().is('mobile');
getDevice().is('tablet');
```

[^1]: https://docs.uaparser.dev/api/main/idata/is.html
